//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Xpressive Websolutions")]
[assembly: AssemblyProduct("Xpressive.Home")]
[assembly: AssemblyVersion("1.0.0.24863")]
[assembly: AssemblyFileVersion("1.0.0.24863")]
[assembly: AssemblyInformationalVersion("1.0.0-beta.11")]
[assembly: AssemblyCopyright("Copyright © 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]

